plugins {
    id 'java'
    id 'eclipse'
    id 'org.springframework.boot' version '4.0.1'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.asciidoctor.jvm.convert' version '4.0.5'
}

group = 'com.project'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

// M4 Mac VS Code 전용 소스 경로 명시
sourceSets {
    main { java { srcDirs = ['src/main/java'] } }
    test { java { srcDirs = ['src/test/java'] } }
}

ext {
    set('snippetsDir', file("build/generated-snippets"))
}

dependencies {
    // [핵심/웹]
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    
    // [통신] WebClient
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    // [보안] 
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'

    // [스케줄러]
    implementation 'org.springframework.boot:spring-boot-starter-quartz'

    // [코드자동화/도구]
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // MyBatis
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'
    // MariaDB 커넥터
    implementation 'org.mariadb.jdbc:mariadb-java-client'

    // SFTP
    implementation 'org.springframework.boot:spring-boot-starter-integration'
    implementation 'org.springframework.integration:spring-integration-sftp'

    // 암호화
    implementation 'org.jasypt:jasypt-spring31:1.9.3'

    // JSch
    implementation 'com.jcraft:jsch:0.1.55'

    //이미지 리사이징 및 압축
    //implementation 'co.adventurelette:thumbnailator:0.4.20'
    implementation 'net.coobird:thumbnailator:0.4.8'

    // 테스트
    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'io.projectreactor:reactor-test'
    
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    outputs.dir snippetsDir
    useJUnitPlatform()
}

tasks.named('asciidoctor') {
    inputs.dir snippetsDir
    dependsOn test
}