spring:
  application:
    name: springboot-thymeleaf

  # [Message] message.xml ?? (?? ?? ??)
  messages:
    basename: i18n/messages
    encoding: UTF-8

  # [Batch] batch.xml ?? (?? ??? ?? ???)
  batch:
    job:
      enabled: false # ?? ? ?? ?? ??
    jdbc:
      initialize-schema: never

  # [AOP] aop.xml ?? (??? ??? ??)
  aop:
    proxy-target-class: true

# [Server] ?? ?? ??
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

# SFTP
sftp:
  host: 123.456.78.90
  port: 22
  user: myuser
  password: mypassword
  directory: /var/www/html/data/