spring:
  application:
    name: springboot-thymeleaf

    # [Multipart] ?? ??? ?? ?? ??
    servlet:
      multipart:
        max-file-size: 50MB          # ?? ? ?? ?? ??
        max-request-size: 100MB      # ? ?? ??(?? ?? ??)? ?? ??
        enabled: true

    # [Thymeleaf] ? ??? ?? ??
    thymeleaf:
      cache: false                   # ?? ??? false? ???? ?? ? ???? ? ?? ???
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML
      encoding: UTF-8

    # [Resources] ?? ??(JS, CSS) ??
    web:
      resources:
        static-locations: classpath:/static/
        chain:
          cache: false               # ??? JS ?? ?? ? ?? ??? ?? ?? ??

  # [Message] message.xml ?? (?? ?? ??)
  messages:
    basename: i18n/messages
    encoding: UTF-8

  # [Batch] batch.xml ?? (?? ??? ?? ???)
  batch:
    job:
      enabled: false # ?? ? ?? ?? ??
    jdbc:
      initialize-schema: never

  # [AOP] aop.xml ?? (??? ??? ??)
  aop:
    proxy-target-class: true


# [Server] ?? ?? ??
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true


# SFTP
sftp:
  hosts:
    - 123.456.78.10
    - 123.456.78.20
    - 123.456.78.30
  port: 22
  user: myuser
  password: mypassword
